---
- name: Install desktop packages
  homebrew:
    name: "{{item}}"
  with_items:
    - hledger
    - watch
    - youtube-dl

- name: Install Node.js packages
  npm:
    name: "{{item}}"
    global: yes
  with_items:
    - mert

- name: Install OSX graphical applications
  homebrew_cask:
    name: "{{item}}"
  with_items:
    - 1password
    - atom
    - dropbox
    - google-chrome
    - iterm2
    - slack
    - spectacle
    - spotify
