---
- name: Install hledger custom commands
  copy:
    src: "{{item}}"
    dest: "{{ ansible_env.HOME}}/bin/{{item}}"
    mode: 0744
  with_items:
    - hledger-networth

- include: roles/desktop/tasks/main.darwin.yml
  when: ansible_os_family == "Darwin"

- include: roles/desktop/tasks/main.ubuntu.yml
  when: ansible_os_family == "Ubuntu"
