---
- name: Install desktop packages
  apt: name={{item}} update_cache=yes state=present
  become: true
  with_items:
    - hledger

- name: Install financial tmux window setup
  copy:
    src: financial.window.sh
    dest: /home/{{ansible_user_id}}/.tmuxifier/layouts/financial.window.sh
