---
- name: Ensure Projects directory
  file:
    state: directory
    mode: 0775
    dest: "{{ ansible_env.HOME}}/Projects"

- name: Clone projects from GitHub
  git:
    dest: "{{ ansible_env.HOME}}/Projects/{{item}}"
    repo: git@github.com:vincecima/{{item}}.git
    update: no
  with_items:
    - steel-config
    - www.vincecima.com
    - how-much-time-left
    - application-config

- include: roles/engineering/tasks/main.ubuntu.yml
  when: ansible_os_family == "Ubuntu"

- include: roles/engineering/tasks/main.darwin.yml
  when: ansible_os_family == "Darwin"
